// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uparfeojuwrjrerdfdjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYXJmZW9qdXdyanJlcmRmZGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTUzNTIsImV4cCI6MjA1NzU5MTM1Mn0.-qZOpyLvvodht3j2bJAdqKmurcu1rDAk5IUNU9qsWW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);